// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnQBXP3fSLP7jJbu1nl0rsKFGEi_Z85Mg',
    appId: '1:57449256335:web:18875a571cbc244fa3e7fa',
    messagingSenderId: '57449256335',
    projectId: 'pingolearn-task',
    authDomain: 'pingolearn-task.firebaseapp.com',
    storageBucket: 'pingolearn-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC00kWi1enR-U4Muqj2aO1rV9UpIXGOXZc',
    appId: '1:57449256335:android:db4abec8179aea35a3e7fa',
    messagingSenderId: '57449256335',
    projectId: 'pingolearn-task',
    storageBucket: 'pingolearn-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqyzZWUk5_QRK9rTWnGlaiqOCQQ4LZ38E',
    appId: '1:57449256335:ios:fb4b8d0b728dc2d3a3e7fa',
    messagingSenderId: '57449256335',
    projectId: 'pingolearn-task',
    storageBucket: 'pingolearn-task.appspot.com',
    iosBundleId: 'com.example.pingolearnTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnQBXP3fSLP7jJbu1nl0rsKFGEi_Z85Mg',
    appId: '1:57449256335:web:0cab73adc9d68987a3e7fa',
    messagingSenderId: '57449256335',
    projectId: 'pingolearn-task',
    authDomain: 'pingolearn-task.firebaseapp.com',
    storageBucket: 'pingolearn-task.appspot.com',
  );
}
